# Generated by Django 3.2 on 2022-05-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rack',
        ),
    ]
