# Generated by Django 3.2 on 2022-05-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan',
            new_name='delivery',
        ),
    ]
